name: liveness_plugin
description: Guardian Liveness Detection SDK Flutter plugin.
version: 0.0.2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: ai.advance.liveness_plugin
    pluginClass: MyLivenessPlugin